insert into public.projects (id,
                             slug,
                             title,
                             description,
                             long_description,
                             image_url,
                             tags,
                             category,
                             employer,
                             role,
                             year,
                             problem,
                             solution,
                             features,
                             tech_stack,
                             featured,
                             display_order,
                             project_url)
values ('9e41f790-9791-49ee-a79f-6d6cc6c3f44d',
        'cohort-hcm',
        'Cohort HCM',
        'A modern, cloud-based Human Capital Management solution engineered for the next generation of digital-first enterprises.',
        'A modern, cloud-based Human Capital Management solution engineered for the next generation of digital-first enterprises.',
        '',
        '{"Laravel","React","Next.js","PostgreSQL"}',
        'PHP/Laravel',
        null,
        'Lead Fullstack Architect',
        '2024',
        'Legacy HCM systems are often characterized by fragmented architectures, sluggish interfaces, and a lack of real-time data synchronization. Enterprises struggle with siloed employee data, manual payroll overhead, and rigid scaling capabilities.',
        'Cohort HCM leverages a unified data layer to eliminate silos. Built with high-frequency performance in mind, it provides an intuitive, consumer-grade experience for employees while offering robust, automated tools for HR teams.',
        '{"Automated onboarding workflows, intelligent leave management, and real-time payroll reconciliation reduce manual intervention by up to 60%.","Built using a micro-services ready approach, ensuring the platform scales effortlessly from startups to global enterprises without performance degradation.","Multi-layer encryption, SOC2 compliance standards, and granular RBAC to keep sensitive human capital data protected."}',
        '[
          {
            "name": "Laravel",
            "icon": "terminal",
            "description": "Core Logic & API"
          },
          {
            "name": "React",
            "icon": "layers",
            "description": "Dynamic UI"
          },
          {
            "name": "Next.js",
            "icon": "sparkles",
            "description": "SSR & Performance"
          },
          {
            "name": "PostgreSQL",
            "icon": "database",
            "description": "Data Persistence"
          }
        ]'::jsonb,
        true,
        1,
        null),
       ('3ab9061e-0e2e-4ef6-bb34-3f4bce90f6a7',
        'smart-inventory',
        'SmartInventory Pro',
        'Enterprise-grade inventory tracking with automated restocking alerts and real-time analytics.',
        null,
        '',
        '{"Laravel","MySQL"}',
        'PHP/Laravel',
        null,
        null,
        null,
        null,
        null,
        '{}',
        '[]'::jsonb,
        false,
        2,
        null),
       ('b631ceca-2e39-4de2-82ad-516393365bbe',
        'edusphere',
        'EduSphere LMS',
        'Scalable e-learning solution managing courses, student progress, and interactive certifications.',
        null,
        '',
        '{"PHP","JavaScript"}',
        'PHP/Laravel',
        null,
        null,
        null,
        null,
        null,
        '{}',
        '[]'::jsonb,
        false,
        3,
        null),
       ('d62e16d8-35f3-4546-8448-feca1b7b5fa6',
        'neural-nexus',
        'NeuralNexus',
        'An AI-driven personal assistant for developers that automates documentation and test generation.',
        null,
        '',
        '{"Python","NLP"}',
        'AI/ML',
        null,
        null,
        null,
        null,
        null,
        '{}',
        '[]'::jsonb,
        false,
        4,
        null),
       ('3ad8e2de-4d7d-41df-89ec-bf72aad5fb69',
        'vault-x',
        'Vault-X',
        'A secure digital wallet featuring instant currency conversion and multi-layer encryption.',
        null,
        '',
        '{"Next.js","Prisma"}',
        'React/Next.js',
        null,
        null,
        null,
        null,
        null,
        '{}',
        '[]'::jsonb,
        false,
        5,
        null)
on conflict (id) do update
    set slug             = excluded.slug,
        title            = excluded.title,
        description      = excluded.description,
        long_description = excluded.long_description,
        image_url        = excluded.image_url,
        tags             = excluded.tags,
        category         = excluded.category,
        employer         = excluded.employer,
        role             = excluded.role,
        year             = excluded.year,
        problem          = excluded.problem,
        solution         = excluded.solution,
        features         = excluded.features,
        tech_stack       = excluded.tech_stack,
        featured         = excluded.featured,
        display_order    = excluded.display_order,
        project_url      = excluded.project_url;
