insert into public.skills (name, skill_category_id)
values ('C',
        (select id from skill_categories where name = 'Languages' limit 1)),
       ('Javascript',
        (select id from skill_categories where name = 'Languages' limit 1)),
       ('PHP',
        (select id from skill_categories where name = 'Languages' limit 1)),
       ('SQL',
        (select id from skill_categories where name = 'Languages' limit 1)),
       ('Typescript',
        (select id from skill_categories where name = 'Languages' limit 1)),

       ('Laravel',
        (select id from skill_categories where name = 'Frameworks' limit 1)),
       ('Next.js',
        (select id from skill_categories where name = 'Frameworks' limit 1)),
       ('React.js',
        (select id from skill_categories where name = 'Frameworks' limit 1)),
       ('NestJs',
        (select id from skill_categories where name = 'Frameworks' limit 1)),
       ('TailwindCSS',
        (select id from skill_categories where name = 'Frameworks' limit 1)),

       ('Git',
        (select id from skill_categories where name = 'Tools' limit 1)),
       ('Gitlab',
        (select id from skill_categories where name = 'Tools' limit 1)),
       ('Supabase',
        (select id from skill_categories where name = 'Tools' limit 1)),
       ('TYPO3',
        (select id from skill_categories where name = 'Tools' limit 1)),
       ('Docker',
        (select id from skill_categories where name = 'Tools' limit 1)),

       ('RAG Architectures',
        (select id from skill_categories where name = 'Research' limit 1)),
       ('Vector DBs',
        (select id from skill_categories where name = 'Research' limit 1)),
       ('LLM Ops',
        (select id from skill_categories where name = 'Research' limit 1))
on conflict do nothing;